version: '3.5'
services:
  flask:
    image: python3/flask-framework-mvc:1.0.2
    build:
      context: .
    entrypoint: /bin/bash
    command: /usr/bin/python3 -m flask_framework.wsgi
    working_dir: /srv/http
    shm_size: 512m
    environment:
      LOG_DIR: /var/log/server/
      LOG_LEVEL: warning
    ports:
      - 4200:4200
    volumes:
      - ./src/:/srv/http/
    depends_on:
      - mysql-server
    links:
      - mysql-server

  mysql-server:
    image: mysql/mysql-server:5.7
    shm_size: 1024m
    environment:
      MYSQL_DATABASE: flask
      MYSQL_ROOT_PASSWORD: "mysql-root-pass"
      MYSQL_PASSWORD: "mysql-pass"
      MYSQL_USER: "mysql-user"
    volumes:
      - ./mysql/:/var/lib/mysql/


  redis:
    image: redis:5.0.7
    command: redis-server /etc/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis.conf