SERVER_ENV:
    APP_NAME: Flask
    APP_KEY : secret-key
    ENV: production
    BIND:
        ADDRESS :  0.0.0.0
        PORT: 4200
    WORKERS: sync
    CAPTURE: false
    STATIC_PATH: static
    TEMPLATE_PATH: template
    SESSION: redis
    THREADS_PER_CORE: 16
    LOG:
        DIR: ${LOG_DIR}
        LEVEL: ${LOG_LEVEL}

DATABASE: {}

LOGINS:
    SAML2

FLASK:
    CONFIG:
        SAML_METADATA_URL : 'your url or file to service provider metadata'
        SAML_DEFAULT_REDIRECT: /test
        #SAML_METADATA_URL : 'config/saml-sp-metadata.xml'

SERVICES:
    redis:
        HOST: localhost
        PORT: 6379
    filesystem:
        PATH: sessions
    memcached:
        HOST: localhost
        PORT: 11211

