SERVER_ENV:
    APP_NAME: Flask
    APP_KEY : 954ccef834147193f429a00097880dce15072c47f6a4e1ce8285fe18bb003bfa2c0e10de01018738e3b898b20a2e8625af19f1d742a1f4037f36603e57c3d468
    ENV: production
    BIND:
        ADDRESS :  0.0.0.0
        PORT: 4200
    WORKERS: sync
    CAPTURE: false
    STATIC_PATH: static
    TEMPLATE_PATH: template
    SESSION: redis
    THREADS_PER_CORE: 16
    LOG:
        DIR: ${LOG_DIR}
        LEVEL: ${LOG_LEVEL}

DATABASE: {}

LOGINS:
    SAML2

FLASK:
    CONFIG:
        SAML_METADATA_URL : 'your url or file to service provider metadata'
        SAML_DEFAULT_REDIRECT: /test
        #SAML_METADATA_URL : 'config/saml-sp-metadata.xml'

SERVICES:
    redis:
        HOST: localhost
        PORT: 6379
    filesystem:
        PATH: sessions
    memcached:
        HOST: localhost
        PORT: 11211

