SERVER_ENV:
    APP_NAME: Flask
    APP_KEY : secret
    ENV: dev
    BIND:
        ADDRESS :  0.0.0.0
        PORT: 4200
    WORKERS: sync
    CAPTURE: false
    SESSION: filesystem
    THREADS_PER_CORE: 16
    LOG:
        DIR: ${LOG_DIR}
        LEVEL: ${LOG_LEVEL}

DATABASES: {}

FLASK:
  CONFIG: {}

SERVICES: 
  filesystem:
    PATH: sessions
